<?php
require_once('app.js');
require_once('API.php');
require_once('Consensus.php');
require_once('Exchange.php');
require_once('Index.php');
require_once('Initiator.php');
require_once('MineBlock.php');
require_once('Puzzle.php');
require_once('Responder.php');
require_once('Sharding.php');
require_once('TokenExchange.php');
require_once('TokenWalletExchangeExtension.php');
